baseURL: https://wiki.synthdiy.com
languageCode: en-us
defaultContentLanguage: en
title: SynthDIY Wiki
theme: synth-wiki-theme
summaryLength: 16

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Modules
      url: /modules
      weight: 2
    - name: Parts
      url: /parts
      weight: 3
    - name: Building Blocks
      url: /building-blocks
      weight: 4
    - name: Knowledge
      url: /knowledge
      weight: 5
    - name: Contribute
      url: /contribute
      weight: 6
    - name: Tags
      url: /tags
      weight: 7
