baseURL: https://wiki.synthdiy.com
languageCode: en-us
defaultContentLanguage: en
title: SynthDIY Wiki
theme: synth-wiki-theme

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Modules
      url: /modules
      weight: 3
    - name: Parts
      url: /parts
      weight: 4
    - name: Building Blocks
      url: /building-blocks
      weight: 5
    - name: Tags
      url: /tags/
      weight: 6
